namespace WordTactics
{
internal class LearningfromLectures
{
//Learning from Lectures
//Introduction
//Making the most of course lectures can be a challenge, particularly when they are not as interesting as you would like them to be. At times, the material you&#8217;re asked to understand can seem intangible for any number of reasons: the content may be dry, the lecturer may be doing their job at too slow or too fast a pace, presentations may be too consistent or boring for your liking, or you may just be feeling out of your element. It is also easy to become distracted by your electronic devices or things you notice in your surroundings. There may even be moments when something about the classroom environment or lecture itself actively discourages your learning.
//No matter the content or context, you can benefit not only from preparing for a lecture, but also from using effective learning strategies during and after the lecture. This page provides examples for you might go about doing so.
//Preparing for a Difficult Lecture
//Thinking actively about what you can do to be focused and successful in your learning environments should begin before class. To boost the probability of understanding and retaining the information taught during lectures, there are helpful steps you can take ahead of time.
//Active reading
//Leading up to a lecture, the expectation will generally be that you read assigned materials and complete any tasks or assignments that accompany those readings. As an added step to highlighting and annotating your materials ahead of time, you might consider the importance of question writing. As you read, pay close attention to things that confuse you or interest you. Writing questions that come to mind as you are reading gives you something to work from when it comes time for lectures. Once you&#8217;re in class, you can ask those questions directly or listen in for answers that may come up during the lecture. By doing this, you have a record of your own curiosities about each topic that you can also ask your instructor more about later on.
//Unplugging
//It&#8217;s no surprise that digital technologies are ubiquitous in today&#8217;s classroom environment. At times, they are necessary and, in some cases, required. Although devices such as laptops or tablets are great for taking notes and completing classwork, there are times when they can get in the way of your learning. When lectures fall dull or become difficult to engage in, the likelihood of using devices for matters unrelated to class is sure to rise. Ahead of lectures, you might restrict access to certain websites or apps on your own. Thankfully, there are apps that help you manage these habits. Here are a few to consider:
//
//Flipd
//SPACE
//Moment
//1Focus
//Offtime
//
//&#160;These applications are among a handful of others that will &#8220;unplug&#8221; you from looming distractions like social media and streaming services. Ensuring that the appropriate settings on your app of choice are activated before each lecture will help you maintain the focus you need in order to grasp difficult or uninteresting material. You may also decide to experiment with this outside of class as a way to schedule in study sessions and tutoring consultations on your own or with a group.
//Striving for accessibility
//Finally, discussing any pressing accessibility issues with your instructor is an important step to take for yourself and your learning. In doing so, you may even be helping your peers. The feeling of being left out during a lecture can be daunting. If you have specific needs in order to be attentive and successful during lectures, then you should voice those needs beforehand. Whether you need your instructor to accommodate lecture audio settings, reserve a specific seat for you, provide a printed copy of presentations before class, or something else entirely, these needs should be brought to their attention as they become necessary. These are just a few among many very real concerns that should be addressed if they will help you learn and retain the material being taught. You may also consider consulting the disability services office at your institution to maintain a record of your needs so that all of your instructors and your advisor(s) are made aware of them. Accessibility concerns can come in between you and your course engagement and participation if you let them. As such, you should always tend to your needs as the semester progresses.
//During a Difficult Lecture
//In the scene of a lecture, there are a few things that tend to come standard. Although the activities taking place during lectures may seem straightforward and expected, it is important to think closely about how you can be more actively involved based on your learning style and the content being taught.
//Taking notes
//When picturing a lecture, note taking is something that seems standard and straightforward. However, a better understanding of which approaches to writing notes works well for you (and which don&#8217;t) can help you retain the information being thrown at you with more clarity. Importantly, your approach to taking notes is something that you may need to alter depending on the course subject, delivery method, instructor teaching styles, and other factors. The best approach for you may be the same in every class or it may vary&#8212;it all depends on how you feel about the material being taught. Writing notes by hand has its pros and cons, just as typing them out does. In the early parts of a semester, it&#8217;s helpful to experiment with different methods to see what goes well and to continue making note of that. Whether you handwrite or type notes, you may decide that standard linear notes, which are continuous and organized in a top-to-bottom manner, are best for you. However, there are also pattern-based approaches to taking notes that are more visual in nature. Here are a few worth exploring for yourself:
//
//The Cornell Method
//Sketch notes
//Table
//Diagram/Spidergram
//
//What&#8217;s important to keep in mind is that these visual methods can be combined with one another or with a linear approach. You may decide to incorporate two or more of them into the design of your notes once you notice what works for you. You may also decide to video and/or audio record lectures and return to them later. It may be necessary to consult with your instructor first if you feel that video/audio recording is going to be a helpful method for you.
//Asking questions
//This is where the work of active reading and question writing can really shine. As a reference point during lectures, the annotations, notes, and questions you have for a given lesson can translate to important discussions in class. The questions you ask based on your own uncertainties or curiosities are likely to help others in the class who may have similar questions, as well. What&#8217;s more is that the answers you receive may lead you to consider further questions you didn&#8217;t think of previously, which you can then ask and write down during class. Speaking up can be difficult but keep in mind that by doing so, you may be doing a whole lot of good for others who are searching for the same answers you are.
//Listening
//Listening during a lecture works really well for some, yet not so well for others. However, you should experiment with finding a balance between listening and taking notes. Copying down slides from a presentation verbatim can take up time that might be better spent listening in for added details or questions that are asked and answered during class. The presentations instructors design for lectures may be available to you online so that you can revisit them outside of class. If not, you can try to reach out to your instructors directly to request them. By listening in, you&#8217;re also better equipped to take note of any points your instructor may have accidentally left out of a presentation and key in on important announcements, dates, directions, or other relevant information that you might otherwise forget.
//After a Difficult Lecture
//At a reasonable time soon after lectures, there are steps you can take to help you practice and better retain what you learned. Of course, when a lecture wraps up for the day, you may have a number of other obligations ahead of you before you can study or work on assignments. Scheduling time in to do these things takes care and attention to details, so you should try to give yourself needed breaks beforehand.
//Revisiting notes and organizing materials
//Whether you have handwritten notes, typed notes, or a combination of both, now is a good time to revisit those. This is also an ideal time to listen closely to lecture recordings (if you have them) and to revisit questions you may have written down prior to the lecture. Some point soon following each lecture, you should check to make sure that any relevant files/documents are saved in appropriate folders and &#8220;nested folders&#8221; (or &#8220;subfolders&#8221;) on your device or in your course binder. Doing so will help prevent confusion or loss of materials down the line. If you house your notes on your digital device(s) but also have some handwritten notes or other print materials from class, you can scan those and upload them accordingly. If you have a phone or tablet, there are apps available to scan physical documents and convert them into a digital format. Being organized is a crucial step toward setting achievable study goals and ensuring that your classwork and study time are spent efficiently.
//Connecting with peers
//Following a lecture, you might consider connecting with peers in your class. Everyone takes in the information taught during lectures differently. Topics that may be a bit boring to you may be interesting to someone else. Moreover, teaching methods that don&#8217;t quite click with your learning style may be the best method for learning and retention for another student in the class. Making connections in class and following up with others to better understand something about a topic is one way to feel more at ease later on. What&#8217;s more is that this is a great step toward forming study groups and making friends. Once you are connected with one or more peers, you can work together to compare notes, ask questions, revisit lectures, complete practice problems, and more.
//Reaching out to instructors
//Every instructor is different. Some may present themselves as more accessible to their students than others. In any case, you should reach out to your instructors either in person after class or by email with any follow-up questions or concerns you may have. This could be related to accessibility, as mentioned earlier, but you may also benefit from asking questions about a specific lesson you&#8217;re struggling with. If you show interest in the material, your instructor may decide to meet with you virtually or in office to help you. Keep in mind that your instructors are also busy. They may suggest tutoring services or additional resources to you, so you should keep a fairly open mind toward any recommendations they offer. You should also consider asking your instructor for available resources if they don&#8217;t suggest any outright.
}
}
