namespace WordTactics
{
internal class RequestingRecommendationLetters
{
//Graduate School Applications: Requesting Recommendation Letters
// 
//Summary:
//During the application process, much of the process is in the hands of the applicant, but recommendation letters are often in the hands of the recommenders. You can't control what someone says, or whether or not they'll meet the deadline, but you can make the process run more smoothly overall. This resource is designed to offer applicants advice on handling the occasionally sticky process of requesting letters of recommendation.
//
//Getting organized
//The first thing you'll want to do when planning for recommendation letters is to organize your application materials. For example: Where are you applying, and to which program(s)? What do you need to send them? What criteria will each school look at when considering applicants? Collect transcripts and test scores as well, and compile a dossier on yourself. You'll want to provide your recommenders with as much information as possible. Even if you think they know you very well, they might find it useful to have reference material. If there are any other particular points on which you'd like them to focus--such as your extracurricular or research activity--be sure that you have a document with that information available for your recommenders. You may also want to include a copy of your r&#233;sum&#233; or CV.
//It's important to compile this information before you determine whom you'll ask for your letters of recommendation, as it can save considerable amounts of time. It also gives your recommenders the impression that you are well prepared. Taking the time to compile this information for potential reviewers can also highlight gaps that might appear in your other application materials, gaps that might be filled by approaching the right person for a letter of recommendation. Perhaps, you are applying to a school that values research, but your research background&#8212;as it is presented in your other application documents&#8212;appears lacking. This means that it might be beneficial to get a recommendation from a professor that has worked with you on research, or that could speak to your potential to carry out meaningful research.
//It may also be helpful to prepare any essays, or writing samples, that you might need in advance. Your potential recommenders may want to see your work in progress. Providing your recommenders with the writing samples that you plan to include in your graduate school application gives them addition reference material while writing your recommendation. Given the time-sensitive nature of these documents, you do not want to be caught unprepared should a recommender ask for a copy of your writing sample. Being unprepared may delay the process, which can have potentially negative consequences for your application.
//Letter of Recommendation Formats
//Unfortunately, there is no standard submission format for recommendation letters. Some school will require that you use a standardized form specific to that school or program, some will accept more traditional letters, and others will require electronic submissions. Be sure that you keep track of the format required for the schools to which you are applying. If the school requires that you use a standardized form that they provide, be sure to take a copy of that form with you when you approach potential recommenders. Also, be sure that you have filled out any required, personal information on the form. This may include information such as: your name and the program to which you are applying. It may also include a box where you can give up your right to see what your recommenders have written. Please note that you are not required to waive your right to see the letters that your recommenders have written. However, not waiving this right may limit what and how your recommender might write their letter.
//Choosing recommenders
//Choosing who you will ask to write your recommendation letters is very important, and if you are fortunate enough to have several potential recommenders, narrow your list down early. You&#8217;ll want to approach your potential recommenders early because many professors and professionals often find themselves inundated with recommendation requests during the application season.
//Your field of study will play a large role in your choice of potential recommenders, as you will want to have at least one person who knows your work, and the field, quite well. If you completed any internships or fieldwork, professionals who you have worked alongside of may be excellent choices for potential recommenders. However, if you are having problems finding potential recommenders from within your field, remember that sheer academic readiness can count for a lot. Professors in related fields may also make good choices, so long as they are familiar with your character and your work ethic.
//Regardless of your field of study, choose recommenders you are certain are familiar with your scholarship, skills, and personality. A boilerplate letter from a big name in your field may not be worth as much as a lesser-known scholar who can speak candidly about you as an individual. It may also be wise to have a backup recommender in case one of your recommenders is unable, for any reason, to complete a letter or two on time.
//Requesting recommendations
//There is no one ideal way to request a recommendation letter&#8212;your relationship with and access to the potential recommender will determine your best course of action&#8212;but there are certain steps you can take to facilitate the process. While you may want to ask some potential recommenders in person, it is always a good idea to follow up with a reference request letter or email. See the OWL's resource on requesting employment references for a model. This allows you to track the date you requested the reference. If they have already agreed in person, reference the conversation, but still include the relevant information about the school to which you are applying, the due date for the letter of recommendation, and the method for letter submission&#8212;paper, electronic, etc. You may also want to include the application materials mentioned above (CV, writing sample, etc.) so that your recommender is prepared.
//Make your requests early. Give your letter-writers at least six weeks to complete the letters, though ideally, eight to ten weeks is a comfortable amount of time. If you are applying to eight or more schools, you may want to begin twelve to fourteen weeks before the deadline.
//Set reminders on your calendar for follow-up dates. Many recommenders will inform you that the letters have been sent, but it is a good idea to follow-up on the status of your letters just in case. This can be done by contacting the school or program to which you are applying. If the school is requiring electronic recommendation letters, it may be possible to track these online. Work backwards from the deadline, setting reminders at one, two, and four weeks before the deadline date. Inquire politely as to the state of your letters, and ask your recommenders if they need any additional information or if they have encountered any problems. Send these follow-ups via e-mail, unless you know a recommender is unlikely to keep up with e-mail. Do not be afraid to follow-up with your recommenders. Professors and other professionals are busy individuals, and they may appreciate the follow-up. Be polite, courteous, and, when necessary, firm in your follow-ups.
//Some schools allow applicants to collect sealed letters and include them with their application packets. While this may cost extra postage, it does allow a measure of certainty regarding the status of the recommendation letters, as you will often collect all of your letters of recommendation for a particular school before sending them in together as part of your application packet. Schools with fully electronic applications may also display information about whether or not a letter has been submitted. If a letter has not been submitted, check in periodically with the schools, even after a recommender says they have sent letters. Materials sometimes get lost in the shuffle, or are misfiled. Keep up with your applications. You may find it helpful to include a spreadsheet or handwritten chart that tracks the status of recommendation letters.
//After the application process
//Many people send their recommenders thank-you cards or small gifts after their applications are complete. A handwritten note, a small gift card, or baked goods are popular choices, though decisions should be tailored to the individuals. This a nice way to thank recommenders, particularly those who have written many recommendations on your behalf. You may need to ask them for further letters down the road. Not everyone is successful on his or her first attempt at getting into graduate school, and even students who are accepted sometimes turn down offers in favor of trying again in the next application season for a better offer. Sending thank-you notes or gifts can pave the way for asking for more letters on subsequent attempts.
//It is also a good idea to keep your recommenders apprised of the outcome of your applications. Do not inundate them with e-mails every time you receive a response from a school, but do let them know about your final results. Your recommenders have invested time and effort in your academic career; they will want to know if their work has paid off.
}
}
