namespace WordTactics
{
internal class ResearchingProgramsPracticalConsiderations
{
//Researching Programs: Practical Considerations
// 
//Summary:
//This section details what to look for in a graduate program--both on a personal and professional level. Personally, you need to consider location, community, campus culture, and other non-academic issues that will affect your happiness. Professionally, you need to figure out your research interest, map the field, research the faculty you&#8217;ll be working with, understand your funding package, calculate work requirements, and analyze research resources.
//
//Applying to graduate school is a very intensive process, and researching the potential graduate programs that you plan on applying to is a puzzle with a great many pieces. Keep in mind that you are not merely choosing an institution at which to get your education; you are also choosing how you will live for the next several years. In order to make an informed decision about what programs to apply to, you need to make sure that your research the program as thoroughly as you can before making any final decisions.
//Community
//Your community in graduate school will be a combination of the community on-campus and the community off-campus. As a graduate student you are far more likely to live off-campus and make connections in the community beyond the university. You may want to consider whether or not you will be able to find services that matter to you such as: religious organizations, access to sports venues, specialty groceries, music venues, volunteer opportunities, or others?
//The on-campus community is also an important consideration. You'll want to consider both the culture of your specific program and the campus-wide community. Get in touch with a few graduate students at the school and try to get a sense of the social scene. Be thinking about the following questions: Are there reading and study groups? Do the faculty have formal or casual relationships with their graduate students? Do graduate students tend to present at conferences together? Are there frequent social gatherings? Who organizes them?
//Additional Certificates and Interdisciplinary Opportunities
//Keeping in mind that finding the right program for graduate study requires a great deal of research, you may also want to consider what other certification opportunities might exist in the programs to which you are applying. For many of graduate students, professional development will necessarily flow over traditional disciplinary boundaries. Different schools and colleges within a university can find ways of making those skills official and measurable through graduate certificates and graduate minors. Look at the requirements for professional certificates and graduate minors. Also, consider the access you will have to faculty and graduate students in other fields of interest that may intersect in your own research.
//Funding Considerations
//Thinking about funding is not simply a matter of comparing the monthly stipends of different programs. You'll want to consider both the full benefits package, which includes the stipend, student fees, travel funds, health care, childcare, as well as optional costs such as parking fees or the cost of a gym membership if the student facilities are inadequate. These considerations should then be compared with the cost of living factors, the number of years you are guaranteed funding, and/or the likelihood of funding if your program awards it on a competitive basis. Many programs also offer additional funding opportunities such as: additional work appointment/increased workload, employment outside the program, and the chance to apply for research grants.
//Work Requirements
//Funding packages also vary greatly in terms of what work you will be expected to perform. You may be expected to teach, tutor, grade, work in a lab, log research hours on a faculty member&#8217;s project, transcribe notes or interviews, staff a library or center, organize events, help the administrative staff, or even be a research subject yourself. While looking for a lighter workload may seem important in the short term, your long-term consideration should be to make sure that the professional experience you gain fits in with your professional goals. Some programs will require relatively little work outside of classes, but when you complete your degree, you will not have much experience. Other programs will require a workload that does not develop the skill set that you need, like having you grade as a teaching assistant when you have no interest in being an educator after you finish your degree. Some programs will have workloads that, in the end, will better prepare you for your career than your course load. In weighing these options, remember that many skills are transferable and most employers in today's economy expect a range of skills.
//Research Resources
//Research costs money, and programs range greatly in the amount of those cost that will be covered. Be sure to look into what research support resources will be available to you at the programs to which you are applying. For example, the library and the Interlibrary Loan (ILL) can save you thousands in journal subscriptions. The existence, or non-existence, of labs and expensive computer software can drastically affect what kind of research you have access to and the kind of research you can carry out. Are there special archives located nearby that will benefit your research? If so, this may save you thousands in travel expenses or weeks of applying for grants. Make sure that the programs that you are applying to have labs that can handle your research needs and have access to the major journals in your field. Many departments may have research sharing programs with other universities.
//Profiling Programs and Statements of Purpose
//Profiling potential graduate programs is meaningful activity because it helps you to ensure that you're making an informed decision about what programs to apply to, and it aids in making that final decision should you be accepted to any of the programs to which you are applying. However, profiling programs can also serve to inform your statement of purpose. Using the information gained while profiling a program, you can better highlight the ways in which you and the program are best fits. By showcasing these areas of "best fit," you can make yourself stand out from among the other applicants in the pool.
}
}
