namespace WordTactics
{
internal class AdviceforWritingApplicationEssays
{
//Advice for Writing Application Essays
// 
//Summary:
//The resources in this section provide a general timeline for undergraduate applications. In this section you will also find more detailed information about each stage in the application process.
//
//Advice for Writing Successful Application Essays
//When you sit down to write your application essays, there is very little left that you can control. You should have already taken, or retaken, the SAT and ACT, your grades from your first three years of high school are set on your transcript, and your recommenders all have their impressions of you that are unlikely to change before the recommendation deadline. The only thing that left in your control is your writing for the application essay.
//As with all things related to your college application, you will need to start drafting your application essay far ahead of the due date. In fact, you should move each school&#8217;s deadline up two weeks so that no unexpected events prevent you from completing and submitting your application. The reason that you need so much time to work on your essay is primarily because many schools will ask you to write about similar topics, but to do so in different ways. You will need enough time to draft essays that address each of these questions or prompts for each school to which you are applying.
//Don't use boilerplate essays. That is, resist the urge to reuse the exact same essay for different schools if each of them is giving you a slightly different writing prompt. You can, of course, adapt the same essay for similar prompts. Many schools do allow you to use the Common Application essay for admission to several participating schools. For more information on the Common Application and to check which schools participate as members, click here.
//Although using the Common Application does simplify the processes, make sure that you review each of the schools&#8217; application requirements. as many of these same schools also request that you submit a second essay along with the Common Application essay. For instance, in addition to answering one of the standard Common Application questions, Amherst College asks that you write an additional essay responding to one of several quotations.
//Before you can start writing your essay, you will need to begin by reading the prompts and questions carefully. Even the Common Application has six prompts that you can choose from. Don&#8217;t feel as though you must choose one immediately after reading them. You should ask yourself what sticks out the most for you after having read through them. Think about what is most salient for you.
//Brainstorm by putting your thoughts on paper. You can free write (writing without stopping or censoring yourself), create word association maps (visually clustering concepts that you feel go together), or keep a journal over the course of several days so that you can collect your thoughts in one place. See the Purdue OWL's PowerPoint on &#8220;Finding your Focus&#8221; for more details on these strategies.
//After you have generated several ideas, reflect on where you find the most intensity or excitement in what you were writing. If nothing jumps out at you, keep brainstorming or talk with others about some possible topics until something grabs you.
//Once you know what want to write about, put a rough draft on paper. Don&#8217;t be afraid of stray thoughts if they lead you to something more interesting than you had set out to write. Just make sure that you eventually come to have a rough draft that is about one thing.
//Look over your draft and check for the following.
//
//Your writing should be personal. After reading your essay, does it seem like anyone could have written this? Make sure that your essay captures who you are.
//You writing should show, not tell, through vivid language. Successful essays relate an experience or analyze a pattern from the writer&#8217;s life. It is not enough to make general claims about what impacted your decision to go to college, for instance; you must elaborate by including evidence that answers &#8220;how&#8221; and &#8220;why&#8221; when you make your claims. 
//
//It is important to note that admissions officers care as much about your structure, style, and insights as they do about your content. That is not meant to add an extra layer of anxiety to your writing process, but to highlight the fact that you don&#8217;t necessarily need to have something life-changing to write about in order to write a successful essay. As Dowhan, Dowhan and Kaufman note in Essays that Will Get You into College, &#8220;Personal does not have to mean heavy, emotional or even inspiring&#8221; (10). In fact, as the authors explain, students might over rely on the significant event that they write about to speak for itself and don&#8217;t &#8220;explain what it meant to them or give a solid example of how it changed them. In other words, they do not make it personal&#8221; (10).
//Finally, your writing should be about a sustained topic. You must use vivid description with a purpose. What is it that you learned because of this experience? What message can you decipher from the series of events that you present? What led you to your conclusions?
//Once you have completed your rough draft, put it away for a few days. Afterwards, read the question again and look through your essay. Ask yourself if the essay answers the prompt. Is it personal? Does it use vivid language? Is it focused on one topic? Rewrite whatever needs to be strengthened. This is a great time to have other people look through your draft and get their reaction. Make sure that you ask someone early, and that you trust this person&#8217;s judgment; they will be putting in a lot of time to help you, so don&#8217;t disregard anything that is inconvenient or that you don&#8217;t want to hear.
//Again, giving yourself plenty of time to work on this essay is vital. You should have enough time to rewrite or restructure your essay based on the feedback that you have received. As you are drafting and revising, feel free to fix any mistakes that you catch in terms of spelling, grammar, and mechanics, but don&#8217;t spend too much time editing early on in the writing process. Working on lower-order concerns can give you the impression that the essay is ready to submit prematurely. Instead, use this time to strengthen the main points of your essay.
}
}
