namespace WordTactics
{
internal class StartingYourApplicationampAskingforLettersofRecommendation
{
//Starting Your Application &amp; Asking for Letters of Recommendation
// 
//Summary:
//The resources in this section provide a general timeline for undergraduate applications. In this section you will also find more detailed information about each stage in the application process.
//
//Starting Your Application
//There is a lot of variety in terms of the actual application requirements for each school. Some schools&#8217; application forms are pages long, while others are only a single sheet. Many colleges will ask that you submit some sort of writing sample along with these forms, but the forms that these writing samples can take varies greatly. Some schools will ask you to write on any topic you wish, while others will ask that you write on a subject they choose. And, others will allow you to submit a graded paper as your writing piece, and some will let you choose. Because each school will have a different process, you must keep a good record of what each of these schools wants. Don&#8217;t simply think that you can remember it all or that you can write down these requirements in different places as a reminder. We forget and we misplace important documents frequently. It may be helpful to keep some sort of visual breakdown of all of your schools' application requirements.
//Casting a wide net
//At this stage, the most important thing you should do is make a list of each school&#8217;s deadlines for their application materials. Some schools have early admissions due dates set for November or December. You should try to meet as many of these early application dates as possible because there is usually less competition than during later application deadlines. There are a lot of materials that you will need to gather before your application will be complete so be sure to start on this early. Although there are clear advantages to submitting a completed application before the early admissions deadline, don&#8217;t rush through just to get your materials in on-time. If you need more time to write a stronger essay, for instance, then you should probably hold off until the next application deadline.
//Even though the application process can be expensive, if going to college is something that you want to pursue, you will have to give yourself as much of an opportunity to be admitted somewhere as possible. Check to see each school&#8217;s admission prerequisites. These are usually posted online. Don&#8217;t let a high GPA requirement stop you from applying to a school (or multiple ones) that you have wanted to attend. Remember that the application essay usually often helps to sway admissions officers more than simple numbers do. That said, do check other schools&#8217; requirements and apply to at least a few schools whose requirements you know you will meet, just in case. As important as knowing how to get into college is knowing how to get out. Make sure you look into the requirements for graduating from each school and ask yourself if you can achieve them in four years.
//Asking for Letters of Recommendation
//Some colleges will require you to have a number of letters of recommendation from individuals who can speak to your talents as a student, or in some other capacity (e.g., community service or leadership). Even if these letters are not required for the main application to the college, often they are required if you wish to apply for competitive scholarships and awards. Therefore, it is never too early to begin thinking about what you are interested in&#8212;both inside and outside of the classroom&#8212;and who could best speak to your abilities.
//When thinking about potential people to ask for recommendation letters, be sure to review why the application that you are filling out is asking you for these letters. For example, if the application instructions state that you should include letters of recommendation that exemplify your involvement in community projects and leadership skills, it might not be a good idea to ask a high school teacher to provide you with a letter if they are only familiar with your work as a student. You may receive better recommendations by asking leaders or supervisors of clubs and organizations that you have worked closely with to write something for you. If the admissions office, on the other hand, wants a letter from someone who is more familiar with your skills as a student, then you will have to think about asking a teacher with whom you have worked closely. If you have had a teacher for more than one year, they may know more about you than other teachers. Here are some suggestions on how to plan for asking for recommendation letters.
//
//Start getting involved in extracurricular activities early in high school. It&#8217;s never too late, so always be on the lookout for sports, clubs, and organizations that you think you might enjoy. Because these will require extra time outside of class, make sure that you can commit to them. Although college admissions officers like seeing letters of recommendation from coaches and supervisors, your grades matter too.
//Make a quick list of which applications absolutely require letters of recommendation and which only encourages them. Ideally, you should try to include letters with all of your applications, but, of course, prioritize the ones that require them.
//Ask your potential recommender politely whether they would be willing to write you a letter of recommendation. Make sure that you give your recommenders the opportunity to politely decline. Not getting a recommendation letter from someone who doesn&#8217;t feel like they would write you a good one is better than ending up with a lukewarm recommendation.
//Be sure to give your recommender as much information about what you are applying to as possible. Is this for a scholarship? Is this for the admission application? What do the instructions ask the recommender to write about? Is the recommendation to be completed as an electronic or hard-copy submission? All of this is very important for the recommender to know. Give them a print out of the instructions and highlight the due dates. Usually, a recommender will be able to write one letter and then print out multiple copies to go with various applications, but you will have to clearly communicate whether or not they will need to write something slightly different for one or several letters, depending on the instructions.
//Above all, remember that people have busy schedules. If you would like to make an early admissions deadline, do not drop this important task on your recommenders&#8217; laps two weeks before you need to turn everything in. Something may come up in their lives resulting in a hurried letter, or no letter at all. Speak with potential recommenders early in the process. It is often wise to provide them with a friendly reminder when necessary.
}
}
