namespace WordTactics
{
internal class SubmittingYourApplicationandFinancialAid
{
//Submitting Your Application and Financial Aid
// 
//Summary:
//The resources in this section provide a general timeline for undergraduate applications. In this section you will also find more detailed information about each stage in the application process.
//
//Submitting Your Application
//Although many schools have electronic applications, many still allow you to turn in your documents through the mail. There are advantages and disadvantages to each method. For instance, working on a hard copy application will cost money and time to ship, it might get lost in the mail, and it often requires careful attention when filling out the forms to avoid mistakes. However, working with an online application will mean frequently saving your work; remembering passwords, usernames, and emails that you use to register an account; and oftentimes printing out copies of your application essay in order to proofread and revise. A system that is being commonly implemented by colleges is the Common Application, an online application that once filled, can be submitted to a number of schools. According to the Common Application website, all applications using this system are considered equally along with those turned in via a colleges&#8217; own electronic application systems. This option can save you time, but you may still need to create multiple accounts for some of your other schools, as not all schools currently accept the Common Application.
//Applying for Financial Aid
//In order to increase your chances of being considered for merit based scholarships, you should start creating and collecting evidence that you deserve aid as early in your high school career as possible. For instance, your transcripts should show not only that you earned good grades in your classes, but also that you challenged yourself by taking difficult courses. Other evidence of academic excellence include your SAT or ACT scores and any academic achievement awards you may have earned while in high school.
//Frequently, however, scholarships are awarded to individuals who are also engaged outside of the classroom through extracurricular and volunteer opportunities in the communities. Quality matters more than quantity here. Make sure you can talk about your experiences in a few areas that interest you in-depth as opposed to listing off numerous activities that seem disconnected or unimportant to you. Typically, you are applying for scholarships provided through the college to which you are applying when you are filling out the main application form. However, you can also search for scholarships from outside the school through such sites as www.fastweb.com or www.scholarships.com, checking in with community organizations, or asking your guidance counselor which scholarships have been awarded to students in previous years.
//You may also qualify for need-based financial aid, but you will have to fill out the Free Application for Financial Student Aid (FAFSA), available at www.fafsa.ed.gov . According to their website, the office of Federal Student Aid is &#8220;responsible for managing the student financial assistance programs authorized under Title IV of the Higher Education Act of 1965. These programs provide grants, loans, and work-study funds to students attending college or career school.&#8221; In order to ensure that you have the best chance possible for receiving aid, you should check each college&#8217;s website for the FAFSA submission deadline, but plan on submitting the application as early in the new year as possible. For instance, some states request that the FAFSA be completed by March, while others provide funding on a first come first serve basis, and so they recommend that students apply right after January 1st.
//The type of funding you might receive will depend on your circumstances. Federal Pell Grants vary according to a student&#8217;s financial need, and unlike loans, do not have to be repaid. You may also qualify for subsidized loans. Unlike with unsubsidized loans, you do not have to pay interest on the money you borrow while you are enrolled in school, during the six-month grace period after you graduate, or during any deferment periods in the future. For more information on federal aid, see the Office of Student Aid website: http://studentaid.ed.gov/
}
}
