namespace WordTactics
{
internal class VisitingSchoolsampAcceptingOffers
{
//Visiting Schools &amp; Accepting Offers
// 
//Summary:
//The resources in this section provide a general timeline for undergraduate applications. In this section you will also find more detailed information about each stage in the application process.
//
//Visiting Colleges and Universities
//The college visit experience varies widely depending not only on the type of school you are applying to and visiting, but also on when you go to visit. Some colleges and universities have formal visit days that serve as an open house for everyone who is interested in applying. Some colleges can create a personal visit for you to speak on an individual basis with students, staff and faculty, or to sit in on classes. Because more students apply than end up being admitted or choosing to accept their admittance, there may be a lot of competition to visit campus. As with everything else on this list, make sure you check in with the admissions office about setting up either type of visit and to clear your schedule well ahead of time.
//Many schools also host visit days for students that have been accepted. The dates vary depending on the colleges&#8217; deadlines for admission. As with visiting before applying, many schools allow you to set up an individual visit day with a planned itinerary after you have been accepted. Despite the similarity in structure, visiting before applying and after acceptance can feel very different. You may feel no pressure at all if you are just visiting without having applied, or conversely, a fervent need to get as much information as possible on your visit in order to write the best application essay possible. After being accepted, you might visit with the understanding that the hard part is over, or, on the other hand, wanting to get as much information as possible in order to make the &#8220;best&#8221; decision on where to go. Despite these scenarios, if you have been accepted, plan on making a trip to the school so that you can make an informed decision about where you want to spend the next few years learning. The more information you have, the easier it will be to make your choice.
//Accepting Your Admission
//As mentioned above, most schools have an early decision deadline close to the end of the year or the beginning of the new year; later deadlines become much more competitive. Regardless of when you submit your application, expect to hear back from each school roughly two weeks to a month after the closest deadline passes (however, keep in mind that you may not hear back from schools regarding financial aid until April). Most schools ask that you notify them whether you plan attend no later than early-May, so depending on when you submit your application you could have a few weeks or a few months to make your decision.
//During this time, be sure to take a breather and reflect on your completion of a successful application process. In the frenzy of applying to numerous schools, you may have forgotten the main drawbacks and benefits to attending each college, so make some time to review where each school stands on financial aid, class sizes, requirements for graduation, and any other aspects of college that will matter to you in the next few years. Ask your teachers, counselor, or any other family and friends who know about your schools to give you their opinions, but ultimately, this is a choice you will have to make for yourself. After this arduous process, be sure to confirm your decision with your schools, letting them know whether you plan to attend in the coming school year or not. This can usually be done through a web link that they will send you.
}
}
