namespace WordTactics
{
internal class PlanningCommunityPartnerships
{
//Planning Community Partnerships
// 
//Summary:
//This resource is a guide for instructors in planning community engagement and navigating community partnerships. Topics include selecting an approach and partner, initiating contact, developing the course, and communicating throughout the partnership.
//
//Integrating community engagement into a course takes planning, communication, and adaptability. This resource is an instructor&#8217;s guide to each phase of planning for community engagement and navigating community partnerships.
//Identifying an Engagement Approach and Potential Community Partners
//You&#8217;ll first want to determine how you&#8217;d like community engagement to fit into your class. Do you want students to complete some kind of project with a community organization? Conduct volunteer hours outside of class? Will the engagement take place throughout the semester or just for one unit? Based on your needs for the class, identify the types of organizations that would be most appropriate to seek out as partners. These might include:
//
//Organizations that need regular volunteers
//Organizations with a focus matching the topic of the course
//Organizations that might need the type of work you&#8217;d like to teach, for example a website or marketing campaign
//
//If you&#8217;re flexible about the organization(s) you partner with, another fruitful strategy for identifying potential partners is to talk to colleagues also engaged in the community. See if your school has engagement/service learning office. Picking up partnerships already established by others can facilitate the collaboration process and help to sustain valuable academic/community relationships.  Student-initiated partnerships: You may be interested in giving students more independence to form their own community partnerships. This can help with student buy-in, but new partnerships can also be challenging to navigate, even for instructors. Students may struggle with coordinating projects, follow-through, and professionalism. If working with college freshmen or younger, it&#8217;s strongly recommended that the instructor at least pre-coordinates with potential partners, provides a list of possible partners to students, and/or encourages students to work with campus groups or organizations they are already affiliated with. More advanced students may be better equipped to seek out new community partnerships by following this resource with instructor guidance.
//Initiating a Partnership
//After your initial research, reach out to an organization you&#8217;d most like to work with by email or phone. Introduce yourself, your course, and potential partnership interests, and request a meeting in person if possible. It&#8217;s ideal to start contacting potential partners at least a month before the course starts to give you plenty of time for planning and reaching out to multiple organizations if needed. Upon meeting with the organization, collaborate to determine how needs for the class can match up with needs of the organization. If the organization doesn&#8217;t have a readily identifiable need for students to contribute to, sharing examples of goals, activities, or projects for the course can help spark thinking about what might be a good fit. This may also be an opportunity for students to join the collaboration process at an early stage: the students themselves could conduct a needs assessment with the organization to determine how they might most usefully contribute. Whatever you decide, it&#8217;s ethically imperative to make sure the partnership is reciprocal in benefitting both the community organization and students. It&#8217;s also important at this stage to set realistic expectations about what students and the organization will each be able to contribute. Be sure to talk through the following questions:
//
//If completing a project, what quality and scope of work can you realistically expect students to produce? Will this level of work truly be useful to the organization?
//If students are volunteering their time, how much time is reasonable? What communication does the organization need in order for the volunteer schedule to run smoothly?
//How often can the organization, instructor, and/or students realistically meet or touch base throughout the partnership? How deeply involved will the organization or instructor be at different stages of students&#8217; progress?
//
//Be sure to follow up your first meeting with an email reviewing what was discussed, at the least. A common document to formalize the partnership is a memo of understanding, which is a brief contract laying out expectations for each party. You may want to do this with students once the course has begun.
//Developing the Course
//Once you&#8217;ve laid the groundwork for your partnership, you&#8217;ll want to return to your course plans to solidify details:
//Engagement parameters: Articulate for students the connection between course goals and the community engagement requirements. For project-based engagement, it&#8217;s a good idea to establish some structure to guide students, but also leave room for flexibility as the project develops. For volunteer-based engagement, be sure to set clear requirements for scheduling and reporting time.
//Reflection: Reflection is a key component for students to reap the most benefits from community engagement. What this looks like will vary based on your class: do you want students to write progress memos for projects, keep journals about their personal response, discuss how things are going in class?
//Dates: Based on your discussion with the community partner about collaboration expectations, outline your major checkpoints for the partnership and integrate them with your schedule for the course. Be sure to report these dates back to your community partner if not already established.
//Communicating throughout the Partnership
//Once the partnership gets moving, it&#8217;s important to maintain an emphasis on communication. What this looks like will depend on your arrangement: Are you mediating communication between students working on projects and the community partner? If so, be sure to touch base whenever plans change and coordinate key questions between students and the organization. If students are doing volunteer hours, be sure to check in periodically with the organization(s) to see how the students are doing and address any concerns. If students are the primary communicators with their partner(s), make sure to set expectations, check-ins, and offer guidance with this process. In every case, you want to balance the need for proactive communication with considerations for time. In other words, emailing every day with a different question can quickly become a drain on your and your partner&#8217;s time. Try to consolidate concerns into reasonable periodic groupings. Also think about the best form of communication for the situation--a long email can often be a much quicker phone call, or maybe scheduling regular meetings best suits your collaboration needs.
//Concluding the Course and/or Partnership
//At the end of a course and/or partnership, it&#8217;s important to bring a sense of closure. A final event is often a nice way to solidify outcomes of the collaboration as well as have a bit of social celebration time. For students, final reflections or letters to the community organization can be a useful and satisfying way to draw final lessons and appreciation of the experience.
//For instructors, the end of a course is also a time to evaluate whether and how the partnership might continue. Sometimes there is a clear next step or course, and sometimes there isn&#8217;t--and that&#8217;s okay. What&#8217;s important is to end the collaboration on a positive note and follow through on final commitments, including any that may fall beyond the end of the course. Often, new opportunities may present themselves at a later time, so determine how best to keep communication lines open and pass information along for potential future collaborators.
}
}
