namespace WordTactics
{
internal class StatementsofPurposeDraftingYourStatement
{
//Statements of Purpose: Drafting Your Statement
// 
//Summary:
//The statement of purpose is perhaps the most important, and most challenging, element of your application packet. This letter needs to reflect who you are and why you would be an asset to the program you are applying to. It needs to make you stand out from the hundreds of other applicants and yet stay within the genre-based expectations for a statement of purpose. This resource provides information on writing statements of purpose specifically for graduate school applications.
//
//Write one essay for each program. Although they may sound similar, each program&#8217;s statement prompts asks for slightly different pieces of information about who you are. You may be fortunate to have two or three similar prompts for a few programs, but even then, remember that you must meld your own interests with the opportunities available at each particular program--so, no two statements should read exactly alike. In essence, be prepared to draft (and continuously revise) dedicated statements for each program application. Don&#8217;t send out a boilerplate essay.
//Attempt to create one unifying theme in your narrative. Some applications ask you to include the answers to broad prompts in your statement. For instance, the only instructions you get may be: describe your goals and preparation to pursue graduate study in no more than 1500 words. Conversely, others may ask you to answer a series of very specific questions such as your reasons for applying to their program in particular, how your background fits into your professional goals, how your past achievements would aid you during your time in graduate school, and what you have learned from your prior professional experience. Regardless of the particular kind of writing situation, attempt to fit your narrative into one unifying theme. For example, if your essay focuses on how family has played an important role in your decision to go to graduate school, do not throw in an experience from your trip to a foreign country as another factor in your decision making process unless it is strongly tied with the overall theme of family. Also, be sure to stick to the word limits.
//Strong statements of purpose answer four important questions that inform admissions committees of who you are professionally and personally.
//Professionally, statements of purpose answer two questions for the committee.
//First: what kind of work are you interested in doing in graduate school?
//Be specific, don&#8217;t make the mistake of thinking that being vague in your focus will reach a wider audience. For instance, if you mainly want to study business ethics with two prominent faculty members who focus on that topic, write that in your statement. Do not worry that you are pigeonholing yourself by being specific and instead list several other areas that you could be interested in. There will not be enough time to go into all of these areas and it will make your statement sound aimless and disconnected.
//Second: why is the program you are applying to a good fit for you?
//This is where your online research on each program comes into play. Be specific about what makes the program that you are applying to your ideal choice. Avoid general statements such as &#8220;your program is one of the best in the country.&#8221; Focus more on the specific things that you think make it great&#8212;for you and your research in particular. If it has a good instructor to student ratio, how will that benefit you? If what separates the program from the rest is that it provides excellent field training before you graduate, how will you take advantage of this? Be specific. You may also talk about your goals after grad school. Where do you see yourself? Does the program have a good history in helping other students get there? You don&#8217;t have to be one hundred percent certain about your future plans; no one will pull your application essay before you graduate and express shock and disappointment if your interests happen to change. But generally, going to graduate school is a huge commitment. Admission committees want to know that you understand this and that you envision some type of gain for your dedication.
//A word of caution: Avoid changing your statement just to get into a program if it is a bad fit for you. You&#8217;ll save yourself time and money down the line.
//Be aware that while it is generally a good idea to be as honest about your intentions as possible, avoid being too candid about your reasons for applying to a certain school if they are less than scholarly. For instance, admission committees do not want to hear that you are applying to their program primarily because of the school&#8217;s proximity to significant others, family, friends; because it is located in a place with a great college town feeling; or, because it offers a variety of funding opportunities (however, you could probably mention this last one in passing if their funding is outstanding among other programs, signaling a dedication to its students&#8217; goals).
//Personally, statements of purpose also answer two questions for the committee.
//First: What matters to you&#8212;and why?
//The committee will receive a lot of data about you. The statement of purpose allows you to give that data meaning. It is important that you not just rephrase whatever is on your CV or resume because this won&#8217;t get at the meaning behind your experiences. A job or a class may have lasted only a few months, but it may have been the impetus for you to go to graduate school because of a unique experience that occurred there. The statement of purpose should give the committee a sense of who you are and how you have personally interpreted events in your life.
//Second: How are you unique from the other candidates?
//Above all, avoid playing it safe with bland language. It can be tempting to resist making yourself stand out in your statement because you don&#8217;t want to ruin your chances by &#8220;sounding weird.&#8221; Ironically, this type of information may be what makes you the most compelling candidate. Graduate program committees receive dozens&#8212;sometimes hundreds&#8212;of applications each year. Make your voice stand out among the rest by showing that you are not only professional but that there&#8217;s a person behind the important decisions you have made. What was the human element that motivated you to get you to where you are?
//Many people wonder whether they should mention their minority status. Generally, you should mention your minority status only if it pertains to your studies. For instance, did working with a minority group (that you belong to) motivate you to go to graduate school? How so? Are you interested in undertaking minority issues once you have earned your degree&#8212;and, if so, in what capacity? For example, once you earn your Masters in Social Work, are you hoping to help Hispanic individuals who suffer from serious and persistent mental illness? Tie this with your background to give this goal some context.
//Remember to switch over between other graduate application tasks such as asking for letters of recommendation, ordering your transcripts, filling out the questionnaire for each school, and so forth. This will break up the writing task and help to re-energize you.
//Works Consulted
//Getting In: A Step-By-Step Plan for Gaining Admission to Graduate School in Psychology. Washington, DC: American Psychological Association. 1997. Print.
//Kaplan, Inc. Get into Graduate School: A Strategic Approach. New York: Simon &amp; Schuster. 2003. Print.
//Stelzer, Richard J. How to Write a Winning Personal Statement for Graduate and Professional School. 3rd. ed. Lawrenceville, NJ: Peterson&#8217;s Publishing, 2002. Print.
//Stewart, Mark Allen. Peterson's How to Write the Perfect Personal Statement. Lawrenceville, NJ: Peterson&#8217;s Publishing, 2009. Print.
}
}
