namespace WordTactics
{
internal class GeneralWritingFAQs
{
//General Writing FAQs
// 
//Summary:
//The following FAQs address various general issues concerning writing. The entries in this section are based on frequently asked questions about writing that have been sent to Purdue OWL Mail Tutors. We encourage you to scan through these before you send your general writing questions to OWL Mail. You should also scan the General Writing section of the Purdue OWL for answers to your questions.
//To access the FAQs, please click here.
//
//I&#8217;m having trouble writing my essay for class. What should I do?
//Essays can be a challenging type of writing, and the OWL provides many useful resources on writing essays. For our collection of resources on essay writing section.
//Writing is so tough! I feel like I can never come up with enough good ideas. Can you help me?
//We recommend constructing a list of topics and drafting some theses about those topics, after which we would be more than happy to aid you in your initial stages of the writing process. For ways to start invention work, we suggest reviewing our resource on invention.
//I&#8217;ve been told that my workplace/business emails aren&#8217;t professional enough. How do I properly write a workplace/business email?
//When writing (and formatting) a business email, use the block format. In other words, do not indent, but use line spaces between paragraphs (as in this paragraph).  The level of complication (in a sentence) should be appropriate to your audience. In other words, if your immediate audience is familiar with the terminology, then it is appropriate to include complex ideas and information.  If this is a first letter to a customer, make sure you develop and maintain a balanced level of professional friendliness in the email. A polite sentence about appreciating their business would be good.  Since it is an email, there is no signature included; you should&#8212;at the very least&#8212;type a closing salutation (e.g., &#8220;Best,&#8221;) and type your name under that. Some people also place their title/position, company name, and contact information in the signature line of an outgoing business emails.
//So, I&#8217;m a graduate student and now it&#8217;s time for me to tackle my thesis/dissertation. This is such a daunting task! Help!
//While the Purdue OWL doesn't currently have resources that pertain to thesis/dissertation writing, you may find it useful to review the website published Professor S. Joseph Levine at Michigan State University.  This is a general, non-discipline-specific guide to getting yourself organized and ready to write the dissertation. You are strongly advised to bring specific questions about your research and the type of document your discipline demands to a professor on your dissertation committee.
//I have to write a critical analysis for one of my classes. Please advise!
//First, you'll want to prepare by reading all the material thoroughly and thinking about some of the different issues raised in your reading. You'll want to do what's called a &#8220;critical read&#8221; of the material, where you don't just accept the information, but&#8212;after you understand it&#8212;you question it. Then, select one of the ideas, which has lingered in your mind because you disagree or are uncomfortable with it, or because you agree with it but believe it needs much more thought. Narrow down your ideas into a question about this idea that you might want to investigate in your paper. Ask yourself what your feelings are about this issue, and what reasons you might use to support your feelings. If you like what you have come up with, then you are ready to form a preliminary thesis. If you do not like it then go back and consider another question from your reading.  Write down a preliminary thesis statement that specifies your topic, states your ideas about this topic, and suggests the arrangement of your paper's argument. Make sure you refer back to your reading and choose details that support your arguments. If you use quotations or refer to the text, it should only be to support your own ideas.  Then try writing a first draft and leaving it for a day. Then go back, reread and revise as necessary.
//I paid one of my friends to write my essay for me. When the teacher found out, he/she failed me, and he/she said that I had violated academic integrity by committing plagiarism. I thought that plagiarism was only if I copied something. I paid for this; why isn&#8217;t this essay mine?
//While you may have paid for the work done on the essay, the work is still not yours. It does not represent your intellectual effort or your original ideas, nor does it represent your abilities with written English. Under most commonly accepted definitions of plagiarism used in most North American academic institutions, plagiarism is not limited to copying text. It also includes, but is by no means limited to: &#8220;ghost writing&#8221;&#8212;having someone else write for you; purchasing a text&#8212;online or from a friend; patchwriting&#8212;copying together various parts of different texts in new ways; borrowing a paper from a friend or fraternity/sorority archives; or turning in unaltered work from a previous course.
//How do I create a &#8220;proper&#8221; bulleted list?
//Consistency is the most important aspect here. If the writer of a text is inserting a bulleted list within a longer, non-bulleted text, and the bulleted text forms a sentence, so to speak, the first letter is usually not capitalized. Here is an example. In all of Virginia Woolf&#8217;s major texts of fiction, she includes:- stream of consciousness,- references to her family, and- feminist issues. The other way to do it is as follows. All of Virginia Woolf&#8217;s major texts of fiction include the following:- Stream-of-consciousness texts- Family references, especially so her mother- Issues directly related to feminism It is important, in the last type, to precede the bulleted list with acomplete sentence. It is also very important to remember parallelism. Inother words, make sure you begin each bulleted list with either a noun oran action verb, but not one or the other. Again, consistency is the key.
//Also, remember that as in an outline, there should never be only one bullet item; you should only use bullets with an actual list.
//What is an absolute phrase?
//An absolute phrase is a phrase that modifies a noun and is connected to a sentence without the use of a conjunction. An absolute phrase could be removed from a sentence and the sentence would still make sense. Here are some examples:
// Marsha looked worried, her fears creeping up on her.
//In this sentence above, "her fears creeping up on her" is the absolute phrase. &#8220;Creeping&#8221; modifies the noun &#8220;fears.&#8221; While the word &#8220;creeping&#8221; modifies the noun &#8220;fears,&#8221; the absolute phrase, &#8220;her fears creeping up on her,&#8221; modifies the complete sentence, &#8220;Marsha looked worried.&#8221;
//I have grammar homework for my language arts/ESL grammar class. I need help with number 27, which deals with appositives. Here&#8217;s what question number 27 says&#8230;
//Unfortunately, OWL staff are unable to answer large numbers of questions that require detailed responses.  If you require more in-depth grammatical information, we recommend books such as the following:  English Grammar in Use by Raymond Murphy The Gregg Reference Manual by William Sabin Rhetorical Grammar by Martha Kolln
//While we understand that some of these books may be expensive, it is possible that your school library, or your local public/municipal library may have these books in their references section.
}
}
