namespace WordTactics
{
internal class RhetoricalSituations
{
//Rhetorical Situations
// Media File: Rhetorical Situations 
//This presentation is designed to introduce your students to a variety of factors that contribute to strong, well-organized writing. This presentation is suitable for the beginning of a composition course or the assignment of a writing project in any class.
//This resource is enhanced by a PowerPoint file. If you have a Microsoft Account, you can view this file with&#160;PowerPoint Online.
//
//Understanding and being able to analyze rhetorical situations can help contribute to strong, audience-focused, and organized writing. The PowerPoint presentation in the Media box above is suitable for any classroom and any writing task. The resource below explains in more detail how to analyze rhetorical situations.
// Understanding Rhetoric
//Writing instructors and many other professionals who study language use the phrase &#8220;rhetorical situation.&#8221; This term refers to any set of circumstances that involves at least one person using some sort of communication to modify the perspective of at least one other person. But many people are unfamiliar with the word &#8220;rhetoric.&#8221; For many people, &#8220;rhetoric&#8221; may imply speech that is simply persuasive. For others, &#8220;rhetoric&#8221; may imply something more negative like &#8220;trickery&#8221; or even &#8220;lying.&#8221; So to appreciate the benefits of understanding what rhetorical situations are, we must first have a more complete understanding of what rhetoric itself is.
//In brief, &#8220;rhetoric&#8221; is any communication used to modify the perspectives of others. But this is a very broad definition that calls for more explanation.
//The OWL&#8217;s &#8220;Introduction to Rhetoric&#8221; vidcast explains more what rhetoric is and how rhetoric relates to writing. This vidcast defines rhetoric as &#8220;primarily an awareness of the language choices we make.&#8221; It gives a brief history of the origins of rhetoric in ancient Greece. And it briefly discusses the benefits of how understanding rhetoric can help people write more convincingly. The vidcast provides an excellent primer to some basic ideas of rhetoric.
//A more in-depth primer to rhetoric can be found in the online video &#8220;In Defense of Rhetoric: No Longer Just for Liars.&#8221; This video dispels some widely held misconceptions about rhetoric and emphasizes that, &#8220;An education of rhetoric enables communicators in any facet of any field to create and assess messages effectively.&#8221; This video should be particularly helpful to anyone who is unaware of how crucial rhetoric is to effective communication.
//&#8220;In Defense of Rhetoric: No Longer Just for Liars&#8221; is a 14-minunte video created by graduate students in the MA in Professional Communication program at Clemson University, and you are free to copy, distribute, and transmit the video with the understanding: 1) that you will attribute the work to its authors; 2) that you will not use the work for commercial purposes; and 3) that you may not alter, transform, or build upon this work.
//Listening to the above podcast and watching the above video should help anyone using this resource to better understand the basics of rhetoric and rhetorical situations.
//A Review of Rhetoric: From &#8220;Persuasion&#8221; to &#8220;Identification&#8221;
//Just as the vidcast and video above imply, rhetoric can refer to just the persuasive qualities of language. The ancient Greek philosopher Aristotle strongly influenced how people have traditionally viewed rhetoric. Aristotle defined rhetoric as &#8220;an ability, in each particular case, to see the available means of persuasion&#8221; (Aristotle Rhetoric I.1.2, Kennedy 37). Since then, Aristotle&#8217;s definition of rhetoric has been reduced in many situations to mean simply &#8220;persuasion.&#8221; At its best, this simplification of rhetoric has led to a long tradition of people associating rhetoric with politicians, lawyers, or other occupations noted for persuasive speaking. At its worst, the simplification of rhetoric has led people to assume that rhetoric is merely something that manipulative people use to get what they want (usually regardless of moral or ethical concerns).
//However, over the last century or so, the academic definition and use of &#8220;rhetoric&#8221; has evolved to include any situation in which people consciously communicate with each other. In brief, individual people tend to perceive and understand just about everything differently from one another (this difference varies to a lesser or greater degree depending on the situation, of course). This expanded perception has led a number of more contemporary rhetorical philosophers to suggest that rhetoric deals with more than just persuasion. Instead of just persuasion, rhetoric is the set of methods people use to identify with each other&#8212;to encourage each other to understand things from one another&#8217;s perspectives (see Burke 25). From interpersonal relationships to international peace treaties, the capacity to understand or modify another&#8217;s perspective is one of the most vital abilities that humans have. Hence, understanding rhetoric in terms of &#8220;identification&#8221; helps us better communicate and evaluate all such situations.
//Works Cited
//Aristotle. On Rhetoric: A Theory of Civic Discourse. 2nd ed. Trans. George A. Kennedy. New York: Oxford UP, 2007.
//Burke, Kenneth. A Rhetoric of Motives. Berkeley: U of California P, 1969.
//Johnson-Sheehan, Richard and Charles Paine. Writing Today. New York: Pearson Education, 2010.
}
}
