namespace WordTactics
{
internal class Setting
{
//Setting
// 
//Summary:
//This presentation is designed to introduce your students to a variety of factors that contribute to strong, well-organized writing. This presentation is suitable for the beginning of a composition course or the assignment of a writing project in any class.
//
//Lastly, all rhetorical situations occur in specific settings or contexts or environments. The specific constraints that affect a setting include the time of author and audience, the place of author and audience, and the community or conversation in which authors and/or audiences engage.
//Time
//&#8220;Time&#8221; in this sense refers to specific moments in history. It is fairly common knowledge that different people communicate differently depending on the time in which they live. Americans in the 1950s, overall, communicate differently than Americans in the 2000s. Not that they necessarily speak a different language, but these two groups of people have different assumptions about the world and how to communicate based on the era in which they live. Different moments in time can be closer together and still affect the ways that people communicate. Certainly, scientists discussed physics somewhat differently the year after Einstein published his theory of relativity than they did the year before Einstein published his treatise. Also, an author and audience may be located at different times in relation to one another. Today, we appreciate Shakespeare&#8217;s Hamlet a bit differently than the people who watched it when it first premiered four hundred years ago. A lot of cultural norms have changed since then.
//Place
//Similarly, the specific places of authors and their audiences affect the ways that texts are made and received. At a rally, the place may be the steps of a national monument. In an academic conference or lecture hall or court case, the place is a specific room. In other rhetorical situations, the place may be the pages of an academic journal in which different authors respond to one another in essay form. And, as mentioned about authors&#8217; and audiences&#8217; backgrounds, the places from which audiences and authors emerge affect the ways that different texts are made and received.
//Community / Conversation
//In various rhetorical situations, &#8220;community&#8221; or &#8220;conversation&#8221; can be used to refer to the specific kinds of social interactions among authors and audiences. Outside of speaking about rhetorical situations, &#8220;community&#8221; usually means specific groups of people united by location and proximity like a neighborhood; &#8220;conversation&#8221; usually refers to fairly intimate occasions of discussion among a small number of people. But in regard to rhetorical situations, both of these terms can have much larger meanings. In any given rhetorical situation, &#8220;community&#8221; and &#8220;conversation&#8221; can refer to the people specifically involved in the act of communication. For instance, consider Pablo Picasso who used cubism to challenge international notions of art at the time he painted. Picasso was involved in a worldwide &#8220;community&#8221; of artists, art critics, and other appreciators of art many of whom were actively engaged in an extended &#8220;conversation&#8221; with differing assumptions about what art is and ought to be. Sometimes, authors and audiences participate in the same community and conversation, but in many instances, authors may communicate in one community and conversation (again, think of Shakespeare four hundred years ago in England) while audiences may participate in a different community and conversation (think of scholars today in any other country in the world who discuss and debate the nature of Shakespeare&#8217;s plays). The specific nature of authors&#8217; communities and conversations affect the ways that texts are made while the specific nature of audiences&#8217; communities and conversations affect the ways that texts are received and appreciated.
}
}
