namespace WordTactics
{
internal class OverviewAfteryouApplytoGraduateSchool
{
//Overview: After you Apply to Graduate School
// 
//Summary:
//The resources in this section will help you prepare your graduate school application(s). This section includes an application-planning timeline, advice on researching and choosing a program, a summary of needed materials and how to develop them, rhetorical principles for building a statement of purpose, and suggestions for how to handle competing offers.
//
//Applying to graduate school is just step one in the long process toward a post-undergraduate education. Once your material is in the mail, you need to start preparing for the outcome. This section offers suggestions on what you should be doing while waiting for results, and what your next step is once you&#8217;re accepted, or rejected, from a program.
//The Wait
//Graduate programs usually make their final decisions in March, so you have a couple of months of sitting on pins and needles ahead of you. Don&#8217;t waste this time. Practice interview questions with friends and professors, and draft polite and insightful questions to ask hiring committees. Not all schools hold interviews before acceptance, but it&#8217;s best to be prepared.
//This might be a good time to visit potential campuses, especially if they&#8217;re within easy driving distance. It&#8217;s hard to get a feel for campus and program culture online or over the phone, so you&#8217;ll want to visit before committing to a school. Most graduate schools don&#8217;t offer funding for campus visits, so the financial burden will be yours whether you&#8217;re accepted or not. If money is tight or you applied at campuses far away from your current location, it might be better to postpone campus visits until you know where you&#8217;re accepted. Then you can visit only those campuses before making your final choice.
//If it&#8217;s the end of April and you have not gotten an acceptance or rejection letter, it&#8217;s allowable to make a polite call to the program asking if the final decisions have been made. More than one call, or a call too early in the year, can be perceived as pushy or even rude.
//The Rejection Letter
//Don&#8217;t let a rejection get you down. Often factors beyond your control, such as academic fit and limited openings, determine who and how many people a program accept. However, you do want to make an effort to understand why you were not accepted. A polite phone call or email asking what you can do to improve your application is acceptable, as long as you are not demanding or passive-aggressive. Present yourself as an applicant who wants to learn. You may not get a response, but it&#8217;s best to try. Don&#8217;t reapply, or apply to other programs, with the same material. You want to fix and improve your material before making a second attempt.
//The Acceptance Letter
//Congratulations! Your graduate career is about to begin. But what do you do if you&#8217;re accepted by more than one program? According to the Council of Graduate Schools, all letters of acceptance should come by April 15 to give applicants plenty of time to see all offers before making their final decision. However, in real life, matters tend to be a bit more complicated. First, letters of acceptance and financial aid package information tends to arrive separately, so you don&#8217;t always know how much funding you will get for each program right away. Second, schools know that not everyone they accept will say yes, so they have a waiting list of applicants who they will extend offers to if one of the initially-accepted declines. If you&#8217;re waiting to hear from one of your top choices, but have gotten acceptance letters from other schools, find out what the absolute last day you can give your answer is. You want to avoid saying yes to a school only to change your mind later. In the small world of academia this can brand you as unprofessional, uncooperative, and rude.
//If you have not made a campus visit yet, this is the time. Meet with professors and students in your potential program and ask questions about the campus, the program, the demands that will be made on your time, and what will be expected of you. Wherever you choose will be your home for the next two to seven years&#8212;do all you can to make sure it&#8217;s a good fit.
//Funding should play a big part in your decision. If you&#8217;re going to law or business school, you&#8217;ll probably have to rely on loans for the duration of these relatively short programs. However, for a terminal degree it is highly suggested that you only attend a program that has offered you tuition remission, grants, and/or a living stipend. Otherwise, the loan burden you take on could cancel out the advantages of having a doctoral degree. Also, opportunities such as teaching and research assistantships provide invaluable experience when you graduate and enter the job market. The choice is always yours, but you need to weigh the importance of a big name university with no funding over a mid-level university with full funding.
}
}
