namespace WordTactics
{
internal class OverviewProcessandMaterials
{
//Overview: Process and Materials
// 
//Summary:
//The resources in this section will help you prepare your graduate school application(s). This section includes an application-planning timeline, advice on researching and choosing a program, a summary of needed materials and how to develop them, rhetorical principles for building a statement of purpose, and suggestions for how to handle competing offers.
//
//There are many parts to a graduate school application. This resource lists possible materials, how to procure or develop those materials, and general tips to follow during the application process.
//The Application Process
//Every school will have different requirements and expectations during the application process&#8212;it is important to deliver exactly what they ask for. A complete, correct, and on-time application packet is expected. If you don&#8217;t deliver, you could be out of the running because of a simple technicality. Pore over the school and department website for each program you are applying for, paying special attention to due dates. Develop a simple and effective filing system, such as labeling folders with the name of each individual university you are applying to and the program&#8217;s application due date. For example, "Purdue 1_30." Build a corresponding electronic folder, saving all electronic correspondences and downloadable forms and applications. Don&#8217;t count on remembering dates, and don&#8217;t keep important documents in a big heap on your desk.
//If you are unsure of what is expected or how an element needs to be turned in, call or email the admissions office. However, before asking questions, make sure that the needed information can&#8217;t be found on the department website. No one likes to be bothered with questions that have already been answered.
//Have someone&#8212;preferably a number of people&#8212;proofread all of your material. This includes your application as well as your personal statement and writing sample. You don&#8217;t want to be the applicant who spells the university&#8217;s name wrong.
//Keep copies of all the materials you turn in. It&#8217;s always possible that your materials will get lost and you&#8217;ll want to replace them quickly. Save each customized personal statement and not just your template. You&#8217;ll want to know exactly what you said on each letter. Call the departmental office a week prior to the deadline to make sure that all your material have been received. This gives you time to submit your copies if your first application went astray.
//Be professional, polite, and courteous throughout the application process. You might be frustrated by the demands made on you, but don&#8217;t take your anger out on the department secretary. One rash word could sabotage your application.
//GRE 
//The Graduate Record Exam, or GRE, is required by the majority of North American graduate schools. The GRE is a timed test that measures verbal reasoning, quantitative reasoning, and analytical writing. This test is highly stylized. Knowing how the test is set up and what kind of thinking is expected of you is almost as important to your score as your actual knowledge and analytical skills. It is highly advisable to buy a GRE study guide. Follow all the directions and take all the sample tests. GRE prep classes are available, but be aware they are quite expensive.
//The GRE is available at roughly 700 test centers in more than 160 countries. The computer-based test is available at almost any time. The paper exam is available three times a year in areas where the computer test is not available. You must take the GRE at a test center, under the supervision of a proctor. You can take the GRE up to five times a year, but be aware that all your scores, not just the best one, will be sent to your prospective schools (About the GRE).
//A small number of schools require the GRE Subject test, which measures knowledge in your area of specialty. Subject test are given at paper-based test centers three times a year in October, November, and April.
//Researching Graduate Programs
//When considering going graduate school, you must think about the experience on a personal and professional level. Personally, you need to consider location, community, campus culture, and other non-academic issues that will affect your happiness. Professionally, you need to figure out your research interest, map the field, research the faculty you&#8217;ll be working with, understand your funding package, calculate work requirements, and analyze research resources.
//For more detailed information or researching and profilling graduate programs, please see the Researching Graduate Programs resource on the Purdue OWL.
//Transcripts
//You need to request official transcripts from all institutions of higher learning you have attended. This is done through the schools' registrar&#8217;s offices or, if you&#8217;re lucky, through an automated online request system. Your transcripts will either be sent directly to the departments you are applying to, or you will be given paper copies in sealed envelopes which you will forward to the correct locations. Most universities need a couple of days&#8217;, or even weeks&#8217;, notice of your intentions and most will charge a fee for this service. You will definitely want to follow up with the programs you are applying to, making sure your transcripts have arrived.
//Letters of Recommendation
//Most departments require three letters of recommendation, preferably from an academic source, such a professor or a department head. These letters are extremely important. Make sure to only ask people that you know well and who will be willing to &#8220;sing your praises.&#8221; If you have taken a substantial amount of time off between earning your undergraduate degree and applying to a graduate program, it may be possible to submit letters from business associates, community involvement associates, and/or your current employer. It is best, however, to have at least one academic recommendation. You might consider taking classes at a local college as a graduate, non-degree seeking student, which will give you a pool of professors to request letters from. It&#8217;s important to follow up with your recommenders. Confirm that they have submitted their letters, and then call each department and make sure the letters have been received. For advice on how to request a letter of recommendation see the a sample letter see Model for Writing a Reference Request Letter on the Purdue OWL. See also, The Purdue OWL's Graduate Schools Application: Letters of Recommendation resource.
//The Statement of Purpose
//The statement of purpose is perhaps the most important, and most challenging, element of your application packet. This letter needs to reflect who you are and why you would be an asset to the program you are applying to. It needs to make you stand out from the hundreds of other applicants; and, yet you must stay within the genre-based expectations for a statement of purpose. It&#8217;s a delicate balancing act. You need to start drafting your personal statement months before it is due, customizing it for each program you are applying to. For more information see the Tailoring Employment Documents resources on the Purdue OWL. Also see the Personal Statement Vidcast on the OWL @ Purdue YouTube Channel.
//Writing Sample
//Some programs will want a sample of your academic writing. Depending on the program you&#8217;re applying for, your writing sample could include: a work of fiction, a poem, a screenplay, a newspaper article, an analytical paper, or a portion of your thesis. It&#8217;s essential that you submit your very best work. It&#8217;s also important to turn in exactly what is requested. If they want a ten-page writing sample and your best paper is fifteen pages, you&#8217;ll need to cut five pages. Don&#8217;t turn it in "as-is" and hope for the best.
//Curriculum Vitae or CV
//Acurriculum vita, or CV, is much like a resume that tells the story of your academic life. A CV should include: contact information, education, publications, professional presentations, honors and awards, teaching experience, research skills and experience, pertinent work experience, and references--typically in that order.
//Unlike a resume your CV should be longer than one page and only include information that pertains to your academic career. Worked at McDonalds while an undergraduate? Unless you&#8217;re applying for a restaurant management program, you shouldn&#8217;t include this on your CV. However, if you served as a research assistant at your university library, you can almost certainly turn this experience into a solid line on your CV.
//At this stage in your academic career you probably don&#8217;t have a stellar CV. Don&#8217;t worry! Graduate school is where you&#8217;ll earn the important lines, such as teaching experience and publications. Don&#8217;t pad your CV with experiences not connected to academia and never include high school awards or experiences. It&#8217;s better to have a short, honest, and professional document than one cluttered with long-ago achievements and off-topic diversions that will only make you look desperate.
//For information on how to write a CV see Writing the Curriculum Vitae.
//Works Cited
//About the GRE. Educational Testing Service, 2012. Web. 2 July 2012.
}
}
