namespace WordTactics
{
internal class ToneMoodandAudience
{
//Tone, Mood, and Audience&#160;
//When thinking about proper diction, an author should consider three main categories:&#160;tone,&#160;mood, and&#160;audience.&#160;&#160;
//Audience&#160;refers to who will be reading the work. Authors tend to write to a particular audience, whether kids, or young adults, or&#160;specialist within a field. The audience can affect the&#160;mood&#160;and&#160;tone&#160;of the writing&#160;because different audiences have different expectations.&#160;&#160;Tone&#160;refers to the author&#8217;s attitude&#8212;how they feel about their subject and their readers. It expresses something of the author&#8217;s persona, the aspects of their personality they wish to show to their readers. For example, are they being funny or serious? Are they writing with fondness or with&#160;derision?&#160;&#160;Mood&#160;refers to the overall atmosphere or feeling of a piece of writing. It is often closely related to&#160;tone, because&#160;the author&#8217;s attitude influences the overall feeling of a text.&#160;It&#8217;s&#160;difficult, for instance, to take a&#160;jovial&#160;tone if the overall mood of the piece ought to be somber, or vice versa.&#160;Wuthering Heights&#160;by Emily Bront&#235;&#160;would be&#160;far less effective&#160;as a gothic&#160;text if&#160;its&#160;spooky atmosphere&#160;was&#160;interrupted by witty, sarcastic&#160;commentary in the style of Jane Austen. 
//Take, for example,&#160;this quote from&#160;Wuthering Heights:&#160;
// &#8220;Catherine Earnshaw, may you not rest as long as I am living. You said I killed you&#8212;haunt me then. The murdered do haunt their murderers. I believe&#8212;I know that ghosts have wandered the earth. Be with me always&#8212;take any form&#8212;drive me mad. Only do not leave me in this abyss, where I cannot find you! Oh, God! It is unutterable! I cannot live without my life! I cannot live without my soul!&#8221;
//This passage displays&#160;heightened emotions and dark themes&#160;through the use of&#160;words like &#8220;ghost,&#8221; &#8220;haunt,&#8221; and &#8220;abyss,&#8221; among others. Consider how much less effective this passage would be if the narration sounded like&#160;Pride&#160;and Prejudice:&#160;&#8220;It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.&#8221;&#160;&#160;
//Using the&#160;appropriate kind&#160;of descriptive words, including&#160;imagery, or vivid language used to paint a mental picture, can convey&#160;mood&#160;and&#160;tone&#160;by helping readers get a&#160;clearer sense of what&#160;they&#8217;re&#160;reading about and how the author thinks and feels about the subject, and thus what&#160;they&#8217;re&#160;supposed to think and feel.&#160;
//Diction can help authors make audiences feel a certain way, like in the example above. Similarly,&#160;different styles&#160;of diction&#160;may&#160;be targeted at different audiences&#8212;there&#8217;s&#160;a good reason&#160;Wuthering Heights&#160;is aimed at&#160;teenagers and&#160;adults rather than young children, for instance. In addition to the content of the text, the elevated and&#160;somewhat antiquated&#160;diction would make it&#160;very challenging&#160;for younger audiences to understand.&#160;Conversely, a paper aimed at an audience of academic experts would&#160;probably be&#160;expected to use more jargon and complicated diction.
//Take, for example, this simplistic description of Pluto&#8217;s orbit&#160;from&#160;Astronomy.com&#8217;s&#160;Astronomy for Kids educational resource:&#160;&#160;
// "Pluto was the ninth planet from the Sun. It orbits our star at a distance of 3.6 billion miles (5.9 billion kim), nearly forty times as far from the Sun as Earth...It takes Pluto 248 Earth years to go around the Sun one time."&#160;
//Compare&#160;this language with&#160;the highly technical language used in&#160;an&#160;Encyclopedia Britannica article on Pluto:&#160;
// &#8220;Pluto&#8217;s mean distance from the Sun, about 5.9 billion km (3.7 billion miles or 39.5 astronomical units), gives it an orbit larger than that of the outermost planet, Neptune. (One astronomical unit [AU] is the average distance from Earth to the Sun&#8212;about 150 million km [93 million miles].) Its orbit, compared with those of the planets, is atypical in several ways. It is more elongated, or eccentric, than any of the planetary orbits and more inclined (at 17.1&#176;) to the ecliptic, the plane of Earth&#8217;s orbit, near which the orbits of most of the planets lie. In traveling its eccentric path around the Sun, Pluto varies in distance from 29.7 AU, at its closest point to the Sun (perihelion), to 49.5 AU, at its farthest point (aphelion).&#8221;&#160;&#160;
//These texts, while essentially saying the same thing, are using wildly different language due to the disparity between their intended audiences.&#160;
}
}
